IDIR =../includes
CC=g++
CFLAGS=-I$(IDIR)

ODIR=obj

_DEPS = lexer.h
DEPS = $(patsubst %,$(IDIR)/%,$(_DEPS))

_OBJ = lexer.o
OBJ = $(patsubst %,$(ODIR)/%,$(_OBJ))

$(ODIR)/%.o: %.cpp $(DEPS)
	$(CC) -c -o $@ $< $(CFLAGS)

lexer: $(OBJ)
	$(CC) -o $@ $^ $(CFLAGS)

.PHONY: clean

clean:
	rm -f $(ODIR)/*.o *~ core $(IDIR)/*~